# Default distributions for pvmlab.
# This file will be created at ~/.pvmlab/distros.yaml on the first run.
# You can add, remove, or modify entries here.

- name: ubuntu-24.04
  distro_name: ubuntu
  version: "24.04"
  arch:
    aarch64:
      qcow2_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"
      kernel_path: "./boot/vmlinuz-6.8.0-87-generic"
      initrd_path: "./boot/initrd.img-6.8.0-87-generic"
    x86_64:
      qcow2_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
      kernel_path: "./boot/vmlinuz-6.8.0-87-generic"
      initrd_path: "./boot/initrd.img-6.8.0-87-generic"

- name: fedora-40
  distro_name: fedora
  version: "40"
  arch:
    aarch64:
      qcow2_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/aarch64/images/Fedora-Cloud-Base-Generic.aarch64-40-1.14.qcow2"
    x86_64:
      qcow2_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2"
